# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks. 
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1
  heroku: circleci/heroku@0.0.10
  slack: circleci/slack@4.4.2


jobs:
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo "deploy my app"
      - slack/notify:
          event: fail
          mentions: '@EngineeringTeam'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
  test-heroku:
    docker:
      - image: 'cimg/base:stable'
    steps:
      # Checkout the code as the first step.
      - checkout
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages
      # If you are using yarn instead npm, remove the line above and uncomment the two lines below.
      # - node/install-packages:
      #     pkg-manager: yarn 
      - run:
          name: Run tests
          command: npm test
      - heroku/deploy-via-git


workflows:
  test-and-deploy:
    jobs:
      - test-heroku
      - slack/on-hold:
          context: slack-secrets
          filters:
            tags:
              only: /^v.*/
          requires:
            - test-heroku
      - deploy:
          filters:
            tags:
              only: /^v.*/
          requires:
            - test-heroku
            - slack/on-hold